services:
  mongodb:
    image: mongo:8.0
    container_name: geolog-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - geolog_mongo_data:/data/db

volumes:
  geolog_mongo_data:
